<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="W00185VDI" name="com.uiFramework.ust.experian.testScripts.BankWiazrdQueries" tests="4" failures="0" timestamp="31 Dec 2018 08:32:58 GMT" time="1.262" errors="1">
  <testcase name="BWAccHolderDeceased" time="0.000" classname="com.uiFramework.ust.experian.testScripts.BankWiazrdQueries">
    <skipped/>
  </testcase> <!-- BWAccHolderDeceased -->
  <testcase name="beforeSuite" time="1.262" classname="com.uiFramework.ust.experian.testScripts.BankWiazrdQueries">
    <error type="com.codepine.api.testrail.TestRailException" message="401 - External auth: Bind: Invalid credentials">
      <![CDATA[com.codepine.api.testrail.TestRailException: 401 - External auth: Bind: Invalid credentialsat com.codepine.api.testrail.TestRailException$Builder.build(TestRailException.java:57)at com.codepine.api.testrail.Request.execute(Request.java:142)at com.uiFramework.ust.experian.utils.TestRailReport.createTestrailRun(TestRailReport.java:71)at com.uiFramework.ust.experian.testbase.TestBase.beforeSuite(TestBase.java:59)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- beforeSuite -->
  <testcase name="BWAccClosed" time="0.000" classname="com.uiFramework.ust.experian.testScripts.BankWiazrdQueries">
    <skipped/>
  </testcase> <!-- BWAccClosed -->
  <testcase name="BWAccClosed" time="0.000" classname="com.uiFramework.ust.experian.testScripts.BankWiazrdQueries">
    <skipped/>
  </testcase> <!-- BWAccClosed -->
</testsuite> <!-- com.uiFramework.ust.experian.testScripts.BankWiazrdQueries -->
